//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("eurorunner_trades", Namespace="", IsNullable=false)]
public partial class trades {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("capacity_trade", typeof(capacityTrade))]
    [System.Xml.Serialization.XmlElementAttribute("capacity_trade_delete", typeof(capacityTradeDelete))]
    [System.Xml.Serialization.XmlElementAttribute("fixed_trade", typeof(fixedTrade))]
    [System.Xml.Serialization.XmlElementAttribute("fixed_trade_delete", typeof(fixedTradeDelete))]
    [System.Xml.Serialization.XmlElementAttribute("swing_nomination", typeof(swingNomination))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class capacityTrade {
    
    private buySell buy_sellField;
    
    private string time_zoneField;
    
    private string codeField;
    
    private decimal priceField;
    
    private bool priceFieldSpecified;
    
    private decimal amountField;
    
    private string networkField;
    
    private string shipperField;
    
    private string book_nameField;
    
    private string traderField;
    
    private locationType location_typeField;
    
    private string locationField;
    
    private category categoryField;
    
    private direction directionField;
    
    private bool directionFieldSpecified;
    
    private firmness firmnessField;
    
    private string commentField;
    
    public capacityTrade() {
        this.location_typeField = locationType.F;
        this.categoryField = category.T;
        this.firmnessField = firmness.F;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public buySell buy_sell {
        get {
            return this.buy_sellField;
        }
        set {
            this.buy_sellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string time_zone {
        get {
            return this.time_zoneField;
        }
        set {
            this.time_zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string network {
        get {
            return this.networkField;
        }
        set {
            this.networkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string shipper {
        get {
            return this.shipperField;
        }
        set {
            this.shipperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string book_name {
        get {
            return this.book_nameField;
        }
        set {
            this.book_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string trader {
        get {
            return this.traderField;
        }
        set {
            this.traderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(locationType.F)]
    public locationType location_type {
        get {
            return this.location_typeField;
        }
        set {
            this.location_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(category.T)]
    public category category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public direction direction {
        get {
            return this.directionField;
        }
        set {
            this.directionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool directionSpecified {
        get {
            return this.directionFieldSpecified;
        }
        set {
            this.directionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(firmness.F)]
    public firmness firmness {
        get {
            return this.firmnessField;
        }
        set {
            this.firmnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum buySell {
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    S,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum locationType {
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    P,
    
    /// <remarks/>
    J,
    
    /// <remarks/>
    G,
    
    /// <remarks/>
    W,
    
    /// <remarks/>
    S,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum category {
    
    /// <remarks/>
    I,
    
    /// <remarks/>
    R,
    
    /// <remarks/>
    T,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum direction {
    
    /// <remarks/>
    N,
    
    /// <remarks/>
    X,
    
    /// <remarks/>
    B,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum firmness {
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    I,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class swingNomination {
    
    private buySell buy_sellField;
    
    private string time_zoneField;
    
    private string contractField;
    
    private string flangeField;
    
    private string capacity_typeField;
    
    private System.DateTime start_dtsField;
    
    private System.DateTime end_dtsField;
    
    private decimal bdrField;
    
    private bool bdrFieldSpecified;
    
    private decimal broField;
    
    private bool broFieldSpecified;
    
    private string networkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public buySell buy_sell {
        get {
            return this.buy_sellField;
        }
        set {
            this.buy_sellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string time_zone {
        get {
            return this.time_zoneField;
        }
        set {
            this.time_zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string contract {
        get {
            return this.contractField;
        }
        set {
            this.contractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string flange {
        get {
            return this.flangeField;
        }
        set {
            this.flangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string capacity_type {
        get {
            return this.capacity_typeField;
        }
        set {
            this.capacity_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime start_dts {
        get {
            return this.start_dtsField;
        }
        set {
            this.start_dtsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime end_dts {
        get {
            return this.end_dtsField;
        }
        set {
            this.end_dtsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal bdr {
        get {
            return this.bdrField;
        }
        set {
            this.bdrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bdrSpecified {
        get {
            return this.bdrFieldSpecified;
        }
        set {
            this.bdrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal bro {
        get {
            return this.broField;
        }
        set {
            this.broField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool broSpecified {
        get {
            return this.broFieldSpecified;
        }
        set {
            this.broFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string network {
        get {
            return this.networkField;
        }
        set {
            this.networkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class capacityTradeDelete {
    
    private string codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class fixedTradeDelete {
    
    private string codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class fixedTradePeriod {
    
    private string flangeField;
    
    private decimal amountField;
    
    private string networkField;
    
    private string codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string flange {
        get {
            return this.flangeField;
        }
        set {
            this.flangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string network {
        get {
            return this.networkField;
        }
        set {
            this.networkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class fixedTrade {
    
    private fixedTradePeriod[] itemsField;
    
    private buySell buy_sellField;
    
    private string time_zoneField;
    
    private string contractField;
    
    private string traderField;
    
    private string codeField;
    
    private decimal priceField;
    
    private bool priceFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("period")]
    public fixedTradePeriod[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public buySell buy_sell {
        get {
            return this.buy_sellField;
        }
        set {
            this.buy_sellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string time_zone {
        get {
            return this.time_zoneField;
        }
        set {
            this.time_zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string contract {
        get {
            return this.contractField;
        }
        set {
            this.contractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string trader {
        get {
            return this.traderField;
        }
        set {
            this.traderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
        }
    }
}
